package com.amlan.userauthenticator.enums;

public enum PermissionTypeEnum {
	VIEW_ALL, VIEW_ANY_GROUP, VIEW_GROUP,
	CREATE_GROUP,
	MAP_ANY_USER_TO_ANY_GROUP, MAP_USER_TO_GROUP,
	ASSIGN_PERMISSION_TO_ALL, ASSIGN_PERMISSION_TO_GROUP
}
